## key=value  \u914D\u7F6E\u6587\u4EF6\u5728src\u6587\u4EF6\u5939\u4E0B\u9762
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
user=root
password=root
initSize=5
maxSize=10